### ISSUE TITLE
how to generate model file

### ISSUE THREAD

**Issue by cizmek777** [KangchengHou/fit-face#1]
Hi, can you do tutorial about how to generate the `basel_face_db.mat` file,
thanks

**Comment by KangchengHou** [comment]
could you check the latest commit 9f29b3739c14f47378e0c140f27667413a227af9? It should work. Let me know if there are futher questions.

**Comment by cizmek777** [comment]
it works. but we need another file here
`fid = fopen(fullfile(metadata_root, 'pp_name.txt'));
`

**Comment by KangchengHou** [comment]
Please see c56baf11bb0ba53dbd9526753891bb92e3823268. I also change the `metadata_root` variable in this commit. There might be some other variables that needs to be changed. You can try running some demos in the `src/demo` folder. Let me know if there are other problems. Thanks for your feedback!
